# Generated by Django 4.2.24 on 2025-09-23 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('header', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(choices=[(True, 'DRAFT'), (False, 'RELEASE')], default=((True, 'DRAFT'), (False, 'RELEASE')))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoPrometheus.author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
